title: AI Discovery Blog 
email: hello@adventis.ai
description: >-
  Discover the latest tools, breakthroughs, and trends in Artificial Intelligence.
url: "https://ruirodsantos.github.io"
# baseurl: "/ai-discovery-blog"  ← ⚠️ MANTÉM COMENTADO SE USAS O DOMÍNIO PADRÃO

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# ⚠️ Adiciona as 2 linhas abaixo
future: true
timezone: Asia/Dubai
