name: Auto-update blog posts

on:
  schedule:
    - cron: "15 8 * * *"   # every day 08:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write

env:
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY || vars.NEWS_API_KEY }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-slugify

      - name: Ensure cache dir
        run: |
          mkdir -p assets/cache
          [ -f assets/cache/.gitkeep ] || : > assets/cache/.gitkeep

      - name: Run updater
        env:
          NEWS_API_KEY: ${{ env.NEWS_API_KEY }}
        run: |
          python scripts/update_posts.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "📰 Auto-update blog posts [skip ci]"
            git push
          fi
