name: Cleanup Old Posts (Jun 04–13)

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run cleanup script
        run: |
          python --version
          python scripts/cleanup_posts.py

      - name: Commit and push deletions
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "🧹 Remove posts 2025-06-04..13 (conteúdo fraco)" || echo "Nada para commitar"
          git push
