name: Rehydrate Existing Posts

on:
  workflow_dispatch:
    inputs:
      since:
        description: "Rehidratar a partir de (YYYY-MM-DD) — opcional"
        required: false
        default: ""
      until:
        description: "Rehidratar até (YYYY-MM-DD) — opcional"
        required: false
        default: ""

jobs:
  rehydrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run rehydration script
        env:
          REHYDRATE_SINCE: ${{ github.event.inputs.since }}
          REHYDRATE_UNTIL: ${{ github.event.inputs.until }}
        run: |
          python scripts/rehydrate_posts.py > rehydrate.log || true
          tail -n +1 rehydrate.log

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/*.md || true
          git commit -m "♻️ Rehydrate thin posts" || echo "No changes"
          git push || true
